apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xsoj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/bootstrap/rhtap-demo-rbri-tenant/rhtap-demo-app/hacbs-test-project-xsoj@sha256:285950a6b2d6ef256d9a72f2c536c50332a0212ef92666a41f420cbd6fd163d2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
